name = "Staking"
contract_trait = "StakingContract"
src_file = "staking-contract.rs"
rename_pairs = [
    [
        "blockchain.set_current_dir_from_workspace(\"contracts/examples/empty\");",
        "// blockchain.set_current_dir_from_workspace(\"relative path to your workspace, if applicable\");",
    ],
]
files_include = [
    "meta",
    "scenarios",
    "src",
    "tests",
    "wasm/Cargo.toml",
    "Cargo.toml",
]